### ISSUE TITLE
Iobroker on Kubernetes

### ISSUE THREAD

**Issue by linux24365** [EugenMayer/helm-charts#64] opened 2024-11-20 14:37 UTC
Hello,
I  know you are discontinuing this, but actually I am interested in your project. Currently I am trying t setup iobroker via helm chart (helm install my-iobroker eugen/iobroker --version 0.2.6) on an K3s cluster ( with 6 Pi5 ) but somehow I am not passing the pending status. The only error I could retrieve is "0/6 nodes are available: 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: true}. preemption: 0/6 nodes are available: 6 Preemption is not helpful for scheduling." 

Would it still be possible to help me out ? (i..e point me to some documentation so that i could start debugging. As for background I am currently running iobroker on a docker swarm system and I judged this setup to be outdated.  I really belief in running iobroker on kubernetes and I think the interest will increase in the near future.

**Comment by EugenMayer** [comment] 2024-11-20 14:56
are you trying to run iobroaker 'multi-head' on several nodes at the same time?

When i stoppped using the chart (since i moved to hassio) i had working:

- [x] the chart was working fine, i could run iobroker with an ingress just fine

Beside my general issues with the 'software/solution' iobroker, which made me us HomeAssistant, i wrote helm charts for both of them and in the end, gave up on both.

The reason i gave up is, i have an IOT network and a 'HOME' network, the former is where all iot devices are located, home is where all the usual mobile phone, 'personal devices' are located. For this to work, mutus was my choice, which in the end proved way to cumbersome to support multi/unicast  and in addition, was horrible documented and defining the different networks was ugly - beside that, you end up so many layering / network namespace that you no longer now which is the cause to block traffic.

This is where HASSIO came in, a slim/'no os' setup of HomeAssistant that i can simply run as a VM, resolving all the network issues in one go. 

Summing it up, the chart should actually work, but it will never work 'multi-headed' - since iobroker is not designed for that. This said, considering the load iobroker generates on a house-size installation, is way too much for a rpi - it's rather to big for some i3s with way more RAM. Not being able to horizontally scale it in this regard will not make you happy running ioBroker on a 'k3s node fleet'  the software is simply not build for that and you will not gain anything. 

If you ever run ioBroker on an rpi for a 'non sanbox'/test installation, you will not run anything else on it, or it will implode. This said, you can then remove the entire k8s overhead and run it on the rpi directly, removing a butload of network issues one has with 'multicast/unicast' iot devices.

Do not get me wrong - i run everyting on k8s (k3s) in my homelab - except one thing, and that is home automation.

**Comment by linux24365** [comment] 2024-11-20 16:00
As far as I understand the settings in the values.yaml file. I am not running iobroker multihead. That is not even my idea. The reason why I moved on was the wish to have a hardware setup which could be used for multiple services ( like influxdb, grafana etc) thus taking advantage of a modern HA config. Opposing the docker world, HA is a combination of nfs or glusterfs (to be discontinued by RedHat) and docker swarm (??) , which was by my experience far from HA. 

Jeff Gerling pointed it out clearly in one of his video talking about what at K3/8s cluster should be for and what this should not be for. So for me it is more the securing of the hardware side then doubling or tripling services.  In what concerns the network setup I use the same approach as you IOT network and home network. For me iobroker is a point of connecting both together bringing my data from the IOT world (mqtt, modbus,) to my home network for monitoring, documentation and (limited) control.  

I think that I will continue to dive into my problem and try to sort out the error, with the goal of having only one instance running. This instance would take care of my data flow (javascript to influxdb) and a small standalone unit which I need anyhow will service the AVAHI protocol.

**Comment by EugenMayer** [comment] 2024-11-20 16:10
Let me know if you could get a multi-network pod up and running with k3s and thus ioBroker. Things like home-bridge and other plugins seem to be still unable to receive multi-cast traffic no matter what i have been using as encapsulation.

I think the only thing that has been working was host, which entirely defeats the networking offered by kubernets and makes a lot of things useless (like ingress and so on).
All in all, even without you heading for HA (which is one of the main goals of k8s and maybe a little less with k3s), the entire network encapsulation concept of k8s with the CNI interface will be a huge hurdle for systems that are purely and stupidly build around multicast/unicast.

Especially when thinking about the cheap and broken implementations of the IOT devices that you might use, having a 100% transparent network, without any rules, is the only way to get those purely implemented IOT devices up and running. And then there are 'we do it this way' based implementation like home-bridge. They want it this way or they wont function - no matter if the network-encapsulation 'should work anyway'.

I had to learn the hard way, that using k8s in this environment is probably (yet) not worth the effort. Neither the IOT devices nor the software side (ioBroker/HomeAssistant) nor the drivers/plugins for the IOT devices within those software solutions are build with any network encapsulation in mind.

They are all build to own the entire network, focusing on simplicity of the implementation of the convenience of the integration only. Security is not on the menu at all.

Nevertheless, if you find anything in the chart, just PR it and i'am happy to add you as a contributor for that chart.

**Comment by linux24365** [comment] 2024-11-28 10:04
Back from debugging, I found an issue in the deployment file. The nodeSelector was set to kuberentes.io/arch: amd64. I changed this to arm64 as I run my k3s cluster on Pi5. I managed to spin up the deployment, but as you mentioned the pod ate all my memory and my cpu on the assigned worker. I've seen a similar behavior on a docker swarm installation. Compared to a normal installation this is way to much, so I am giving up on this too. I need to think of a new concept now, will see. But anyhow, thanks for your comments and thanks for the exchange.

**Closed** 2024-11-29 06:17 UTC
